### ISSUE TITLE
Support Go 1.12

### ISSUE THREAD

**Issue by sue445** [mercari/docker-appengine-go#7]
Now, Go 1.12 is available on appengine
https://cloud.google.com/appengine/docs/standard/go112/

Do you have scheduled release for `mercari/appengine-go:1.12`?

**Comment by sonatard** [comment]
I created this docker image in Mercari, Inc but I left Mercari.

New repository is here.
https://github.com/gcpug/docker-appengine-go
gcpug is Google Cloud Platform User Group in Japan.

I currently use Google App Engine Go. I will continue to maintain until migrate to a better solution than AppEngine.
